### ISSUE TITLE
ROCm support

### ISSUE THREAD

**Issue by renich** [Teriks/dgenerate#9]
I've read the docs on ROCm support but even, though, it installed correctly (on a brand new python 3.12 venv) it didn't work when running `--help`. Or, rather, it did but bitsandbytes complained a lot:

```console
$ dgenerate --help
Could not load bitsandbytes native library: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "/home/renich/tmp/dgenerate/venv/lib64/python3.12/site-packages/bitsandbytes/cextension.py", line 85, in <module>
    lib = get_native_library()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/renich/tmp/dgenerate/venv/lib64/python3.12/site-packages/bitsandbytes/cextension.py", line 64, in get_native_library
    cuda_specs = get_cuda_specs()
                 ^^^^^^^^^^^^^^^^
  File "/home/renich/tmp/dgenerate/venv/lib64/python3.12/site-packages/bitsandbytes/cuda_specs.py", line 39, in get_cuda_specs
    cuda_version_string=(get_cuda_version_string()),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renich/tmp/dgenerate/venv/lib64/python3.12/site-packages/bitsandbytes/cuda_specs.py", line 29, in get_cuda_version_string
    major, minor = get_cuda_version_tuple()
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/renich/tmp/dgenerate/venv/lib64/python3.12/site-packages/bitsandbytes/cuda_specs.py", line 24, in get_cuda_version_tuple
    major, minor = map(int, torch.version.cuda.split("."))
                            ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'

CUDA Setup failed despite CUDA being available. Please run the following command to get more information:

python -m bitsandbytes

Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
and open an issue at: https://github.com/bitsandbytes-foundation/bitsandbytes/issues
...
```

In any case, here's my whole installation procedure on Fedora 41 x86_64 and with a rx 7900 xtx (gfx1100):

```bash
# create venv and activate it
python3.12 -m venv venv
source venv/bin/activate

# install stuff
pip3 install dgenerate[ncnn]==4.4.2 --extra-index-url https://download.pytorch.org/whl/rocm6.2/
```

Additionally, I've found this: https://huggingface.co/docs/bitsandbytes/main/en/installation?backend=AMD+ROCm#multi-backend

And this actually worked (it installed and `--help` worked fine):

```bash
pip install --force-reinstall dgenerate[ncnn] 'https://github.com/bitsandbytes-foundation/bitsandbytes/releases/download/continuous-release_multi-backend-refactor/bitsandbytes-0.45.0.dev0-py3-none-manylinux_2_24_x86_64.whl' --extra-index-url https://download.pytorch.org/whl/rocm6.2/
```

I haven't tried it yet. I'm looking how to define where models are downloaded. My guess is that I'll have to define the hugging face env variable to direct models somewhere else but... still reading `--help`. 

I'll report back in a while.

**Comment by Teriks** [comment]
I hadn’t realized bitsandbytes had this platform issue when I included it quite a while back

the way you have mentioned might be the only way for that dependency to be installed correctly in its current state of development

I will spin up an AMD machine this week and see what else should be sorted out in the branches I am developing on currently for ROCm since dependencies have changed a bit since I last confirmed working install doc & working in general

If that is the only way for that dependency to install correctly I will add it to doc, thank you

**Comment by renich** [comment]
BTW, generation works fine. I have my own python script for generating (no ONNX) and it yields ~3 it/s while using `sd_embed`. With `dgenerate` I am down to 2s/it. Without `sd_embed`, I am down to ~2 it/s. 

Let me know if you want a separate ticket for this or not interested.

**Comment by Teriks** [comment]
Sure, if there is a speed difference feel free to describe in another issue.  Options like ``—model-cpu-offload`` or ``—model-sequential-offload`` will slow down generation in favor of VRAM optimization, other than that I am not sure what might be happening there without comparing the generation script to the calls into diffusers generated by dgenerate

so if you would like or are willing, providing the script or some reduced form of what it is doing would be helpful in another issue, + whatever dgenerate command is being used

**Comment by Teriks** [comment]
HF_HOME controls the cache directory for anything downloaded from huggingface, there is a separate cache implemented for misc downloaded files from elsewhere as well, the env vars are described at https://github.com/Teriks/dgenerate?tab=readme-ov-file#file-cache-control (fyi, happened to gloss over, sorry)

**Comment by Teriks** [comment]
> I've read the docs on ROCm support but even, though, it installed correctly (on a brand new python 3.12 venv) it didn't work when running `--help`. Or, rather, it did but bitsandbytes complained a lot:
> 
> ```
> $ dgenerate --help
> Could not load bitsandbytes native library: 'NoneType' object has no attribute 'split'
> Traceback (most recent call last):
>   File "/home/renich/tmp/dgenerate/venv/lib64/python3.12/site-packages/bitsandbytes/cextension.py", line 85, in <module>
>     lib = get_native_library()
>           ^^^^^^^^^^^^^^^^^^^^
>   File "/home/renich/tmp/dgenerate/venv/lib64/python3.12/site-packages/bitsandbytes/cextension.py", line 64, in get_native_library
>     cuda_specs = get_cuda_specs()
>                  ^^^^^^^^^^^^^^^^
>   File "/home/renich/tmp/dgenerate/venv/lib64/python3.12/site-packages/bitsandbytes/cuda_specs.py", line 39, in get_cuda_specs
>     cuda_version_string=(get_cuda_version_string()),
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/renich/tmp/dgenerate/venv/lib64/python3.12/site-packages/bitsandbytes/cuda_specs.py", line 29, in get_cuda_version_string
>     major, minor = get_cuda_version_tuple()
>                    ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/renich/tmp/dgenerate/venv/lib64/python3.12/site-packages/bitsandbytes/cuda_specs.py", line 24, in get_cuda_version_tuple
>     major, minor = map(int, torch.version.cuda.split("."))
>                             ^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: 'NoneType' object has no attribute 'split'
> 
> CUDA Setup failed despite CUDA being available. Please run the following command to get more information:
> 
> python -m bitsandbytes
> 
> Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
> to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
> and open an issue at: https://github.com/bitsandbytes-foundation/bitsandbytes/issues
> ...
> ```
> 
> In any case, here's my whole installation procedure on Fedora 41 x86_64 and with a rx 7900 xtx (gfx1100):
> 
> ```shell
> # create venv and activate it
> python3.12 -m venv venv
> source venv/bin/activate
> 
> # install stuff
> pip3 install dgenerate[ncnn]==4.4.2 --extra-index-url https://download.pytorch.org/whl/rocm6.2/
> ```
> 
> Additionally, I've found this: https://huggingface.co/docs/bitsandbytes/main/en/installation?backend=AMD+ROCm#multi-backend
> 
> And this actually worked (it installed and `--help` worked fine):
> 
> ```shell
> pip install --force-reinstall dgenerate[ncnn] 'https://github.com/bitsandbytes-foundation/bitsandbytes/releases/download/continuous-release_multi-backend-refactor/bitsandbytes-0.45.0.dev0-py3-none-manylinux_2_24_x86_64.whl' --extra-index-url https://download.pytorch.org/whl/rocm6.2/
> ```
> 
> I haven't tried it yet. I'm looking how to define where models are downloaded. My guess is that I'll have to define the hugging face env variable to direct models somewhere else but... still reading `--help`.
> 
> I'll report back in a while.

The problem I am discovering with this install method is that pip pulls down the last non conflicting version where ``bitsandbytes`` is not listed as a dependency, i.e. ``degenerate==4.3.0`` if you check ``dgenerate --version``.  pip dependency resolution is remarkably terrible with stuff like this so I am likely to remove this dependency, as it is also non functional with Apple MPS.

loading quantized weights with ``bitsandbytes`` is not implemented in my software yet, though I was intending to try at some point.  I have not been able to even get it working reliably on NVIDA cards either.

there has not been a consensus on how quant loading should work in diffusers yet, there are many libs / methods in the running for this as you may have seen with the ``sd_embed``, which is using ``torchao`` in its examples.

I currently only have implemented very slow pre-quantization of weights using ``optimum-quanto``

**Comment by Teriks** [comment]
Should be fixed in [v4.5.0](https://github.com/Teriks/dgenerate/releases/tag/v4.5.0).  The new release is up on PyPI and should be installable with pip with ROCm support using 

```bash

pip install dgenerate[ncnn]==4.5.0 --extra-index-url https://download.pytorch.org/whl/rocm6.2/

```

**Comment by renich** [comment]
I can confirm this worked fine. Thanks a lot.

**Comment by iwr-redmond** [comment]
Note that bitsandbytes support for OSX and ROCm is currently in preview, with regularly updated wheels being published [here](https://github.com/bitsandbytes-foundation/bitsandbytes/releases/tag/continuous-release_multi-backend-refactor).
